// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.BData;

#nullable disable

namespace Stock.BData.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230701201027_Base")]
    partial class Base
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.BData.Data.Entity.Informe", b =>
                {
                    b.Property<int>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProd"));

                    b.Property<int>("IdProductos")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProd");

                    b.HasIndex("IdProductos");

                    b.HasIndex(new[] { "IdProd" }, "Informe_IdProd_UQ")
                        .IsUnique();

                    b.ToTable("Informes");
                });

            modelBuilder.Entity("Stock.BData.Data.Entity.Productos", b =>
                {
                    b.Property<int>("IdProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductos"));

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("PrecioProducto")
                        .HasMaxLength(2)
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("IdProductos");

                    b.HasIndex(new[] { "IdProductos" }, "Productos_IdProductos_UQ")
                        .IsUnique();

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Stock.BData.Data.Entity.Informe", b =>
                {
                    b.HasOne("Stock.BData.Data.Entity.Productos", "IdProducto")
                        .WithMany()
                        .HasForeignKey("IdProductos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProducto");
                });
#pragma warning restore 612, 618
        }
    }
}
